apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app
  namespace: secure-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: secure-apps
  name: app-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: secure-apps
subjects:
- kind: ServiceAccount
  name: sa-app
  namespace: secure-apps
roleRef:
  kind: Role
  name: app-reader
  apiGroup: rbac.authorization.k8s.io
